# default configuration with all args specified

# dataset arguments
data_dir: "/home/gmvincen/class_work/ece_792/Unsupervised-Domain-Adaptation/data"
source_dataset: "amazon_source"
target_dataset: "webcam_target"

# output arguments
tensorboard_log_dir: "runs/"
model_path: "models/"

# training arguments
model: "DANN"
encoder: "resnet50"
batch_size: 64
epochs: 30
lr: 0.0001
perturb: True 